### ISSUE TITLE
Set custom status code for not found guild condition in various APIs

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-serverComm#110]
### Description:
There are several APIs in our application that operate with guildId. Currently, when we call these APIs for a specific guild that does not exist in our database, the API responds with status codes 400 (Bad Request) or 404 (Not Found). The goal of this issue is to set a custom status code 440, to better represent this specific condition (guild not found).

### Tasks:
- [x]  GET: api/v1/guilds/:guildId/channels + update tests + update swagger
- [x]  GET: api/v1/guilds/:guildId/selected-channels  + update tests + update swagger
- [x]  GET: api/v1/guilds/:guildId + update tests + update swagger
- [x]  PATCH: api/v1/guilds/:guildId + update tests + update swagger
- [x]  POST: api/v1/guilds/:guildId/disconnect + update tests + update swagger
- [x]  GET: api/v1/guilds/discord-api/:guildId + update tests + update swagger
