### ISSUE TITLE
Onboarded Contributors Funnel Graph

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-serverComm#119]
### Description:
We need a new API to create a line graph for visualizing the flow of onboarded contributors. This task includes the implementation of the code, the tests, and the API documentation in Swagger.

### Tasks:
- [x]  Implement Integration Tests: Develop robust integration tests for the API to ensure its functionality and reliability. Make sure these tests cover all possible use cases and edge cases.
- [x] Complete the mock API which already exist
- [x] Implement Swagger Documentation: Develop comprehensive Swagger documentation for the API to facilitate future understanding, maintenance, and usage of the API.

###  data
Based on the given sample, the response from your API should resemble the following format:
```
{
    categories: ['21 Jan', '22 Jan', '23 Jan', '24 Jan', '25 Jan', '26 Jan', '27 Jan'],
    series: [
        { name: 'joined', data: [2, 4, 6, 8, 10, 2, 4] },
        { name: 'newlyActive', data: [2, 4, 6, 8, 10, 2, 4] },
        { name: 'stillActive', data: [2, 4, 6, 8, 10, 2, 4] },
        { name: 'dropped', data: [2, 4, 6, 8, 10, 2, 4] }
    ],
    joined: 36,
    newlyActive: 36,
    stillActive: 36,
    dropped: 36,
    joinedPercentageChange: 100,
    newlyActivePercentageChange: 100,
    stillActivePercentageChange: 100,
    droppedPercentageChange: 100,
}
```

### Field Mapping:
Based on the **memberActivity** collection, the UI widget names map to the field names in the **memberActivity** collection as follows:
-    **joined** corresponds to **all_joined** in the collection
-    **newlyActive** corresponds to **all_new_active** in the collection
-    **stillActive** corresponds to **all_still_active** in the collection
-    **dropped** corresponds to **all_dropped** in the collection

### References:
-   [Member Activities Collection](https://github.com/RnDAO/tc-dbComm#memberactivities)
-   [Figma](https://www.figma.com/proto/t9z3mjdIoorswonK00Ttsa/TogetherCrew-prototype?node-id=1-2783&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1%3A49&hide-ui=1)
