### ISSUE TITLE
Active Members Composition Members Breakdown Table

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-serverComm#125]
### Description:
The goal of this issue is to create an API endpoint that provides data for the active members composition breakdown table. This data should be structured with pagination and offer filter options for activity composition, roles, and username. Furthermore, the API should provide sorting capabilities for the username and DAO membership date.

### About the Activity Composition:

- During our discussions, there were differing opinions about how to handle users with multiple activity compositions. Initially, Daniel suggested that we check each activity member type individually. For example, if a user is identified as a vitalMembers, there would be no need to include the user in the other activity composition types (totActiveMembers, newlyActive, consistentlyActive). Similarly, if a user is consistentlyActive, there would be no need to include them in the (totActiveMembers, newlyActive) categories. but in the end, I think we decided to check all activity types of a user, allowing a user to appear in multiple activity compositions simultaneously. If my understanding is incorrect, please correct me.

- We had a brief discussion about a potential category called 'Others', but we didn't reach a final decision. please add the final decision in the comment section here

### Notes for Frontend Developer:

The API is designed with the following features:
Pagination: Pagination is built into the API, with a default limit set to **10** results per page and a default page set to **1**. You can modify these defaults via the query string parameters limit and page.

**Filtering:** The API supports filtering by **activityComposition**, **roles**, and **username**. For activityComposition, valid values include **"all_active", "all_new_active", "all_consistent", "all_vital", "others"**. The roles filter accepts an array of Discord role IDs, and username is for filtering based on a string username.

**Sorting:** The results can be sorted by **username** and **joinedAt**. Sorting syntax is as follows: sortBy=<field>:<asc|desc>. For multiple fields, separate the sort fields by a comma. By default, the results are sorted by username in ascending order (A-Z).

**API Response Structure:** The API responds with the following structured JSON object:

`
{
  "results": [
    {
      "name": "Behzad",
      "avatar": "b50adff099924dd5e6b72d13f77eb9d7",
      "roles": [
        {
          "roleId": "discordRoleId1",
          "name": "role1",
          "color": "#000000"
        }
      ],
      "activityComposition": [
        "Newly active",
        "Vital"
      ],
      "joinedAt": "2022-05-30T15:46:52.924+00:00"
    }
  ],
  "limit": 10,
  "page": 1,
  "totalPages": 2,
  "totalResults": 20
}
`

### Tasks:
- [x]     Add Tests for Get Discord Roles: Create robust test cases to ensure the functionality and reliability of the "Get Discord Roles" API.
- [x]     Implement Get Discord Roles API: Develop the "Get Discord Roles" API to retrieve available Discord roles by guildId.
- [x]     Add Tests for the Active Members Composition Breakdown Table API: Develop comprehensive test cases for the Active Members Composition Breakdown Table API.
- [x]     Implement the Active Members Composition Breakdown Table API: Develop the Active Members Composition Breakdown Table API as per the specifications given.
- [x]     Add Swagger Documentation: Create detailed documentation for the newly created APIs in Swagger for future maintenance and understanding.

### References:
-   [Member Activities Collection](https://github.com/RnDAO/tc-dbComm#memberactivities)
-   [Figma](https://www.figma.com/proto/t9z3mjdIoorswonK00Ttsa/TogetherCrew-prototype?node-id=1-2783&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1%3A49&hide-ui=1)

**Comment by daniel-ospina** [comment]
Your understanding of the activity composition is correct. We check for all the categories a member can belong to and showcase them all.

**Comment by amindadgar** [comment]
For the part in about activity decomposition 
> During our discussions, there were differing opinions about how to handle users with multiple activity compositions. Initially, Daniel suggested that we check each activity member type individually. For example, if a user is identified as a vitalMembers, there would be no need to include the user in the other activity composition types (totActiveMembers, newlyActive, consistentlyActive). Similarly, if a user is consistentlyActive, there would be no need to include them in the (totActiveMembers, newlyActive) categories. but in the end, I think we decided to check all activity types of a user, allowing a user to appear in multiple activity compositions simultaneously. If my understanding is incorrect, please correct me.

We reached the final verdict that we want to show them as the roles (tags) column. So we would include all the activity types.

Also for the part 
> We had a brief discussion about a potential category called 'Others', but we didn't reach a final decision. please add the final decision in the comment section here

I agree with Daniel to put the Others but I think it could be a bit confusing for the user what it is, so I think they could discuss it more in UX meeting call.
