### ISSUE TITLE
Active Members Onboarding Members Breakdown Table 

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-serverComm#132]
### Description:
The goal of this issue is to create an API endpoint that provides data for the active members onboarding breakdown table. This data should be structured with pagination and offer filter options for activity composition, roles, and username. Furthermore, the API should provide sorting capabilities for the username and DAO membership date.

### Notes for Frontend Developer:
The API is designed with the following features:
Pagination: Pagination is built into the API, with a default limit set to **10** results per page and a default page set to **1**. You can modify these defaults via the query string parameters limit and page.

**Filtering:** The API supports filtering by **activityComposition**, **roles**, and **username**. For activityComposition, valid values include **"all_joined", "all_new_active", "all_still_active", "all_dropped", "others"**. The roles filter accepts an array of Discord role IDs, and username is for filtering based on a string username.

**Sorting:** The results can be sorted by **username** and **joinedAt**. Sorting syntax is as follows: sortBy=<field>:<asc|desc>. For multiple fields, separate the sort fields by a comma. By default, the results are sorted by username in ascending order (A-Z).

**API Response Structure:** The API responds with the following structured JSON object:

`
{
  "results": [
    {
      "name": "Behzad",
      "avatar": "b50adff099924dd5e6b72d13f77eb9d7",
      "roles": [
        {
          "roleId": "discordRoleId1",
          "name": "role1",
          "color": "#000000"
        }
      ],
      "activityComposition": [
        "Dropped",
        "Newly active"
      ],
      "joinedAt": "2022-05-30T15:46:52.924+00:00"
    }
  ],
  "limit": 10,
  "page": 1,
  "totalPages": 2,
  "totalResults": 20
}
`

### Tasks:
- [x]     Add Tests for the Active Members Onboarding Breakdown Table API: Develop comprehensive test cases for the Active Members Onboarding Breakdown Table API.
- [x]     Implement the Active Members Onboarding Breakdown Table API: Develop the Active Members Onboarding Breakdown Table API as per the specifications given.
- [x]     Add Swagger Documentation: Create detailed documentation for the newly created APIs in Swagger for future maintenance and understanding.

### References:
-   [Member Activities Collection](https://github.com/RnDAO/tc-dbComm#memberactivities)
-   [Figma](https://www.figma.com/proto/t9z3mjdIoorswonK00Ttsa/TogetherCrew-prototype?node-id=1-2783&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1%3A49&hide-ui=1)
