### ISSUE TITLE
Integration amendments

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-serverComm#14]
# Tasks
## Add new server
New API for adding additional guilds.
**Flow:** someone has already added a guild and then they need to add another guild. for this we need a new API with different access permissions. 

## List of servers which our bot has been added too 
We need to show the connect guild.

- [ ] Update DB - Add new fields for in progress analyze, createdAt and etc
- [ ] Create API for listing the connected guilds 
- [ ] API for disconnecting bot from a guild

**Comment by mehrdadmms** [comment]
Integration should be coming soon as we must discuss the flow

**Comment by mehrdadmms** [comment]
Resolved by #16
